### ISSUE TITLE
Wageningen scraper

### ISSUE THREAD

**Issue by DaanVanVugt** [DaanVanVugt/Taxila#79]
RSS feed

**Comment by margriet321** [comment]
Haico Minkhorst <[jira@wursupport.atlassian.net](mailto:jira@wursupport.atlassian.net)

**Comment by DaanVanVugt** [comment]
I doubt we can get an answer by mailing their ticketing system general address, I'll see if Shauna can make a request there.

**Comment by DaanVanVugt** [comment]
RSS feed at https://www.wur.nl/nl/Resources/RSS/Agenda.htm but does not include event date

**Comment by DaanVanVugt** [comment]
https://www.wur.nl/en/Resources-1/RSS/Calendar.htm for english
