### ISSUE TITLE
Feature-flag for materials support

### ISSUE THREAD

**Issue by DaanVanVugt** [DaanVanVugt/Taxila#9]
First look up nice ways to do feature flags.
Perhaps https://www.johnnunemaker.com/rails-feature-flags/

Will need to:
- [ ] setup feature flag configuration (through environment variables?)
- [ ] disable routes
- [ ] remove some parts of views
- [ ] alter/remove some validations
- [ ] ...

**Comment by fbacall** [comment]
Hi!

Just snooping in your repository after seeing your accidental PR.

Another fork of TeSS has implemented feature flags and other things that you may find useful: https://github.com/dresa-org-au/TeSS/blob/master/app/views/layouts/_header.html.erb#L145-L171

We're in the process of getting those changes merged back upstream into ElixirTeSS/TeSS in the coming weeks, so you may want to keep an eye on that.
