### ISSUE TITLE
eScience zonder events mag weg op contentprovider

### ISSUE THREAD

**Issue by margriet321** [DaanVanVugt/Taxila#98]
staat er nu twee keer 1x met en 1x zonder
<img width="237" alt="lege escience" src="https://user-images.githubusercontent.com/106070240/185376075-6b99e280-6145-4a38-8040-4ae259e1bce0.png">

**Comment by DaanVanVugt** [comment]
Het zijn twee losse eventbrite pagina's, ook op de tweede komen events. Ik denk voorlopig even het beste laten staan.
